apiVersion: apps/v1 # For versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:   # Data that helps  uniquely identify the object (using name, UID and namespace)
  name: {{.Release.Name }}
spec:  # What state you desire for the object
  selector:  # The selector field defines how the deployment finds which pod to manage
    matchLabels:
  {{- include "helm-charts.selectorLabels" . | nindent 6}}
  replicas: {{.Values.replicaCount}}  # Tells the deployment to run 3 pods matching the template
  template:
    metadata:
      labels:  # Labels are used as identifying attributes for objects such as pods and replication controller.
    {{- include "helm-charts.labels" . | nindent 8}}
    spec:
      containers:
        - name: {{.Values.container.name}}
          image: {{.Values.image.repository}}
          imagePullPolicy: {{.Values.image.pullPolicy}}
          ports:
            - containerPort: {{.Values.service.targetport}}
